/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FluxRouteImport } from './routes/flux'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxRoute = FluxRouteImport.update({
  id: '/flux',
  path: '/flux',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/flux': typeof FluxRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/universe': typeof UniverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/cookie-policy'
    | '/flux'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/cookie-policy'
    | '/flux'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/acceptable-use'
    | '/cookie-policy'
    | '/flux'
    | '/privacy'
    | '/terms-and-conditions'
    | '/universe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FluxRoute: typeof FluxRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UniverseRoute: typeof UniverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flux': {
      id: '/flux'
      path: '/flux'
      fullPath: '/flux'
      preLoaderRoute: typeof FluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FluxRoute: FluxRoute,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UniverseRoute: UniverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
